import type { Question } from "./types";

// Vetted question bank — 104 items across EA1955, Sabah Labour Ordinance,
// and Sarawak Labour Ordinance. Tagged by law, topic, difficulty, type.
// All references are to provisions as amended.

export const QUESTIONS: Question[] = [
  // ---- Wages (EA1955) ----
  { id: "w1", type: "mcq", law: "EA1955", topic: "wages", diff: 1,
    text: "What is the national minimum wage in Malaysia under the Minimum Wages Order 2022?",
    options: ["RM1,200", "RM1,500", "RM1,800", "RM2,000"], answer: 1,
    why: "The Minimum Wages Order 2022 set the rate at RM1,500 per month, applying nationally to most employers from 1 May 2022." },
  { id: "w2", type: "mcq", law: "EA1955", topic: "wages", diff: 2,
    text: "For overtime worked on a normal working day, what is the minimum overtime rate under EA 1955?",
    options: ["1.0× ordinary rate of pay", "1.5× ordinary rate of pay", "2.0× ordinary rate of pay", "3.0× ordinary rate of pay"], answer: 1,
    why: "Section 60A(3)(a) requires not less than 1.5× the hourly rate of pay for overtime on normal working days." },
  { id: "w3", type: "tf", law: "EA1955", topic: "wages", diff: 2,
    text: "Wages must be paid no later than the 7th day after the end of the wage period.",
    options: ["True", "False"], answer: 0,
    why: "Section 19 requires payment of wages within 7 days after the wage period ends." },
  { id: "w4", type: "mcq", law: "EA1955", topic: "wages", diff: 3,
    text: "On a paid public holiday that an employee actually works, the minimum extra pay (on top of holiday pay) is at:",
    options: ["1× hourly rate", "2× hourly rate", "3× hourly rate", "4× hourly rate"], answer: 1,
    why: "Section 60D(3): an employee who works on a paid public holiday is entitled to two days' wages at the ordinary rate of pay in addition to the holiday pay." },

  // ---- Hours (EA1955) ----
  { id: "h1", type: "mcq", law: "EA1955", topic: "hours", diff: 1,
    text: "After the 2022 amendments (effective 1 Jan 2023), the maximum normal working hours per week under EA 1955 is:",
    options: ["40 hours", "45 hours", "48 hours", "50 hours"], answer: 1,
    why: "Section 60A was amended to reduce the maximum from 48 to 45 hours per week, effective 1 January 2023." },
  { id: "h2", type: "tf", law: "EA1955", topic: "hours", diff: 2,
    text: "An employer may require an employee to work overtime exceeding 104 hours in any one calendar month without exemption.",
    options: ["True", "False"], answer: 1,
    why: "The Employment (Limitation of Overtime Work) Regulations cap overtime at 104 hours per month. Exceeding that requires Ministerial exemption." },
  { id: "h3", type: "mcq", law: "EA1955", topic: "hours", diff: 1,
    text: "How many rest days per week must an employer provide?",
    options: ["None required", "At least one whole day", "At least two whole days", "Half a day"], answer: 1,
    why: "Section 59: at least one whole day in each week as a rest day." },

  // ---- Leave (EA1955) ----
  { id: "l1", type: "mcq", law: "EA1955", topic: "leave", diff: 1,
    text: "After the 2022 amendments, paid maternity leave under EA 1955 is:",
    options: ["60 consecutive days", "90 consecutive days", "98 consecutive days", "120 consecutive days"], answer: 2,
    why: "Section 37 was amended to raise paid maternity leave from 60 to 98 consecutive days, effective 1 January 2023." },
  { id: "l2", type: "mcq", law: "EA1955", topic: "leave", diff: 2,
    text: "A married male employee is entitled to paternity leave of:",
    options: ["3 consecutive days", "5 consecutive days", "7 consecutive days", "14 consecutive days"], answer: 2,
    why: "New Section 60FA grants 7 consecutive days of paid paternity leave per confinement, up to 5 confinements, subject to qualifying conditions." },
  { id: "l3", type: "mcq", law: "EA1955", topic: "leave", diff: 2,
    text: "An employee with 3 years of service is entitled to paid annual leave of (minimum):",
    options: ["8 days", "12 days", "16 days", "20 days"], answer: 1,
    why: "Section 60E: less than 2 years → 8 days; 2 to <5 years → 12 days; 5+ years → 16 days." },
  { id: "l4", type: "tf", law: "EA1955", topic: "leave", diff: 2,
    text: "Paid sick leave entitlement increases with the employee's length of service.",
    options: ["True", "False"], answer: 0,
    why: "Section 60F: 14 days (<2 yrs), 18 days (2–<5 yrs), 22 days (5+ yrs), plus up to 60 days hospitalisation per year (totals capped at 60)." },
  { id: "l5", type: "mcq", law: "EA1955", topic: "leave", diff: 3,
    text: "A pregnant employee notifies her employer of intended maternity leave, but the employer dismisses her citing 'restructuring' 4 weeks before her due date. The dismissal is most likely:",
    options: ["Lawful — restructuring is a valid reason", "Lawful if 4 weeks notice is paid", "Unlawful — protection against dismissal during the maternity protection period", "Lawful if the employee earns above RM4,000"], answer: 2,
    why: "Section 41A prohibits termination of a female employee during her maternity protection period. Burden is on the employer to prove dismissal is on grounds entirely unrelated to pregnancy." },

  // ---- Termination (EA1955) ----
  { id: "t1", type: "mcq", law: "EA1955", topic: "termination", diff: 2,
    text: "Where the contract is silent, an employee with 3 years of service is entitled to notice of termination of:",
    options: ["4 weeks", "6 weeks", "8 weeks", "12 weeks"], answer: 1,
    why: "Section 12(2): 4 weeks (<2 yrs), 6 weeks (2 to <5 yrs), 8 weeks (5+ yrs), where the contract is silent." },
  { id: "t2", type: "tf", law: "EA1955", topic: "termination", diff: 3,
    text: "Before terminating an employee for misconduct, the employer must hold a 'due inquiry' — a domestic inquiry where the employee can answer the allegations.",
    options: ["True", "False"], answer: 0,
    why: "Section 14(1) requires a due inquiry before dismissal for misconduct. Skipping it is a common reason dismissals are overturned at the Industrial Court." },
  { id: "t3", type: "mcq", law: "EA1955", topic: "termination", diff: 3,
    text: "An employee dismissed without just cause and excuse may file a representation under the Industrial Relations Act 1967 within:",
    options: ["14 days", "30 days", "60 days", "90 days"], answer: 2,
    why: "Section 20 of the IRA 1967: a representation must be made to the Director General of Industrial Relations within 60 days of dismissal." },
  { id: "t4", type: "mcq", law: "EA1955", topic: "termination", diff: 4,
    text: "Termination benefits under the Employment (Termination and Lay-Off Benefits) Regulations 1980 apply primarily to employees earning:",
    options: ["Any salary level", "Up to RM2,000/month", "Up to RM4,000/month", "Up to RM5,000/month"], answer: 2,
    why: "Although EA 1955 itself was extended to all employees in 2023, the Termination & Lay-Off Benefits Regulations remain limited to employees earning RM4,000 and below." },

  // ---- Recruitment / Compliance ----
  { id: "r1", type: "mcq", law: "EA1955", topic: "recruitment", diff: 2,
    text: "Under Section 60M (anti-discrimination, added 2022), it is unlawful to discriminate against an employee on grounds such as gender, religion, race, marital status, or:",
    options: ["Star sign", "Disability", "Football team", "Hair colour"], answer: 1,
    why: "Section 60M empowers the DG to inquire into and decide disputes regarding discrimination in employment, expressly covering disability among other protected grounds." },
  { id: "r2", type: "tf", law: "EA1955", topic: "compliance", diff: 2,
    text: "Under Section 61, employers must keep a register of every employee with prescribed particulars for not less than six years from the latest entry.",
    options: ["True", "False"], answer: 0,
    why: "Section 61 requires a register of every employee with prescribed particulars, retained for at least six years from the date of the latest entry." },
  { id: "r3", type: "mcq", law: "EA1955", topic: "compliance", diff: 2,
    text: "Forced labour under Section 90B carries penalties of up to:",
    options: ["RM5,000 fine", "RM10,000 fine, or 2 years imprisonment, or both", "RM50,000 fine or 1 year imprisonment", "RM100,000 fine, or 2 years imprisonment, or both"], answer: 3,
    why: "Section 90B (added 2022) prohibits forced labour and provides for a fine up to RM100,000, imprisonment up to 2 years, or both." },

  // ---- Sabah Labour Ordinance ----
  { id: "sb1", type: "mcq", law: "Sabah", topic: "compliance", diff: 1,
    text: "Which statute is the primary labour law in Sabah?",
    options: ["Employment Act 1955", "Sabah Labour Ordinance (Cap. 67)", "Industrial Relations Act 1967", "Workers' Minimum Standards of Housing Act 1990"], answer: 1,
    why: "Employment in Sabah is governed by the Sabah Labour Ordinance (Cap. 67), separate from the EA 1955 which applies to Peninsular Malaysia and the Federal Territory of Labuan." },
  { id: "sb2", type: "tf", law: "Sabah", topic: "leave", diff: 2,
    text: "The Sabah Labour Ordinance has been amended to expand maternity leave and introduce paternity leave broadly in line with the EA 1955 reforms.",
    options: ["True", "False"], answer: 0,
    why: "Sabah's Labour Ordinance has been progressively aligned with the EA 1955 amendments — including expanded maternity leave and the introduction of paternity leave provisions." },
  { id: "sb3", type: "mcq", law: "Sabah", topic: "wages", diff: 2,
    text: "A factory in Tawau pays its workers monthly. Wages must be paid:",
    options: ["Within 3 days of the wage period", "Within 7 days of the wage period", "By the 15th of the following month", "At any time agreed by the parties"], answer: 1,
    why: "Like EA 1955, the Sabah Labour Ordinance requires payment of wages not later than the 7th day after the end of the wage period." },

  // ---- Sarawak Labour Ordinance ----
  { id: "sk1", type: "mcq", law: "Sarawak", topic: "compliance", diff: 1,
    text: "Which statute primarily governs employment in Sarawak?",
    options: ["Sabah Labour Ordinance", "Sarawak Labour Ordinance (Cap. 76)", "Employment Act 1955", "Industrial Relations Act 1967"], answer: 1,
    why: "The Sarawak Labour Ordinance (Cap. 76) is the primary labour statute applicable to most employees in Sarawak." },
  { id: "sk2", type: "tf", law: "Sarawak", topic: "hours", diff: 2,
    text: "The Sarawak Labour Ordinance, like EA 1955, sets a maximum of 45 hours per week for normal working hours after recent amendments.",
    options: ["True", "False"], answer: 0,
    why: "Sarawak's Labour Ordinance has been amended to harmonise key working-hour limits with the EA 1955 reforms — the 45-hour weekly cap being one such change." },
  { id: "sk3", type: "mcq", law: "Sarawak", topic: "leave", diff: 3,
    text: "A timber-processing employer in Sibu denies paternity leave to a male engineer. Most likely position under current law:",
    options: ["Lawful — paternity leave is voluntary", "Lawful — only EA 1955 has paternity leave", "Likely unlawful — Sarawak Labour Ordinance now provides paid paternity leave", "Lawful only if collective agreement is silent"], answer: 2,
    why: "Recent amendments aligned the Sarawak Labour Ordinance with EA 1955 maternity/paternity reforms; eligible male employees are now entitled to paid paternity leave subject to qualifying criteria." },

  // ---- Scenarios ----
  { id: "sc1", type: "scenario", law: "EA1955", topic: "termination", diff: 3,
    who: "HR Manager, KL fintech",
    setup: "Aiman, a software engineer, is repeatedly late. After three written warnings, you'd like to terminate him for misconduct. Your CEO says, 'Just give him a termination letter on Monday — we've warned him enough.'",
    text: "What's the most defensible next step?",
    options: ["Issue the termination letter immediately as the CEO requested", "Offer a mutual separation with one month's salary, no inquiry needed", "Convene a domestic inquiry with notice of charges and a chance to be heard", "Demote Aiman without inquiry as a lesser punishment"], answer: 2,
    why: "Section 14(1) requires due inquiry before dismissal for misconduct. A domestic inquiry — with charges, evidence, and the right to be heard — protects the dismissal from being set aside as without just cause and excuse under IRA 1967 Section 20." },
  { id: "sc2", type: "scenario", law: "EA1955", topic: "leave", diff: 2,
    who: "Founder, 12-person agency",
    setup: "Sara has worked for you for 6 years and is expecting her first child. She asks how much paid maternity leave she gets.",
    text: "What is the minimum she is entitled to under EA 1955?",
    options: ["60 consecutive days", "90 consecutive days", "98 consecutive days", "12 weeks"], answer: 2,
    why: "Section 37 (as amended): 98 consecutive days of paid maternity leave. The 60-day figure is pre-2023." },
  { id: "sc3", type: "scenario", law: "EA1955", topic: "compliance", diff: 3,
    who: "New office manager",
    setup: "Your CEO wants to retain employee resumes, salary slips, and disciplinary records to 'save server costs,' wiping anything older than 12 months.",
    text: "Which course is most legally aligned?",
    options: ["Wipe everything older than 12 months — storage is expensive", "Keep employee registers/records as required by Section 61 (retain particulars; do not destroy prematurely)", "Keep only resumes; wipe disciplinary records", "Move records to a USB stick at home"], answer: 1,
    why: "Section 61 requires keeping a register with prescribed particulars of every employee. Disciplinary and wage records are also required for inspection. Premature deletion can attract penalties and weaken the employer's defence in disputes." },

  // ---- True/False bonus pool ----
  { id: "tf1", type: "tf", law: "EA1955", topic: "hours", diff: 1,
    text: "An employee can be required to work more than 12 hours in any one day with no exception.",
    options: ["True", "False"], answer: 1,
    why: "Section 60A(4): no employee shall be required to work more than 12 hours in any one day, save in specified emergency or essential-service circumstances." },
  { id: "tf2", type: "tf", law: "EA1955", topic: "wages", diff: 1,
    text: "Deductions for advances of wages may be made without the employee's written consent.",
    options: ["True", "False"], answer: 1,
    why: "Section 24 limits deductions; advances and other discretionary deductions generally require the employee's written consent and/or approval of the Director General." },
  { id: "tf3", type: "tf", law: "EA1955", topic: "recruitment", diff: 2,
    text: "Sexual harassment complaints must be inquired into by the employer.",
    options: ["True", "False"], answer: 0,
    why: "Part XVA (Sections 81A–81G) obliges an employer who receives a complaint of sexual harassment to inquire into the complaint, with limited exceptions." },
  { id: "tf4", type: "tf", law: "EA1955", topic: "compliance", diff: 1,
    text: "Flexible working arrangement requests are explicitly recognised in EA 1955.",
    options: ["True", "False"], answer: 0,
    why: "New Sections 60P–60Q (added 2022) allow an employee to apply in writing to vary hours, days, or place of work; the employer must approve or refuse with reasons within 60 days." },

  // ---- Spot the violation ----
  { id: "sv1", type: "violation", law: "EA1955", topic: "hours", diff: 2,
    setup: "A fulfilment centre in Klang requires staff to work 10-hour shifts, six days a week. There is no rest day. Overtime hours are paid at the same hourly rate as normal hours.",
    text: "Which violations apply?",
    options: ["No weekly rest day (Section 59)", "Overtime not paid at the statutory uplift (Section 60A)", "Both of the above", "Neither — the contract permits this"], answer: 2,
    why: "Section 59 requires at least one rest day per week; Section 60A requires overtime to be paid at not less than 1.5× the ordinary hourly rate on normal working days. Both are clearly breached." },
  { id: "sv2", type: "violation", law: "EA1955", topic: "leave", diff: 3,
    setup: "A startup founder fires an employee on her first day back from maternity leave, without inquiry, citing 'team fit.'",
    text: "Most likely characterisation:",
    options: ["Lawful — probation gives wide discretion", "Likely unlawful — risk of unjust dismissal under IRA 1967 and breach of maternity protection", "Lawful — 'team fit' is a valid ground", "Lawful only if employee earns over RM4,000"], answer: 1,
    why: "Termination immediately after maternity leave invites an unjust-dismissal claim. The employer must show genuine, non-pregnancy-related grounds via due inquiry — 'team fit' without process rarely survives the Industrial Court." },

  // ---- Decision simulator ----
  { id: "ds1", type: "decision", law: "EA1955", topic: "compliance", diff: 3,
    who: "You — Head of People",
    setup: "A junior staffer reports that her senior manager makes repeated suggestive remarks. She asks: 'Please don't make a formal complaint — just talk to him.' What do you do?",
    options: [
      { label: "Quietly speak to the manager and move on", score: -5,
        why: "Risky. EA 1955 Part XVA requires the employer to inquire into a sexual harassment complaint once received. Informal handling can expose the company to liability and the staffer to retaliation." },
      { label: "Ask the staffer to put it in writing, then trigger a formal inquiry", score: 8,
        why: "Best practice. A documented complaint and a properly run inquiry preserves the staffer's rights and the employer's legal position under Part XVA." },
      { label: "Refer her to counselling and close the matter", score: -3,
        why: "Insufficient. The statutory inquiry obligation isn't discharged by referring the complainant to counselling." },
      { label: "Tell her you can't act unless HR receives a formal complaint", score: 2,
        why: "Partly correct on form, but you should actively support her to lodge it and explain anti-retaliation safeguards." }
    ] },
  { id: "ds2", type: "decision", law: "EA1955", topic: "termination", diff: 4,
    who: "You — HR Business Partner",
    setup: "Your COO wants to retrench 8 of 40 staff next week, citing weak quarter. He proposes 'first in, first out — easier to defend.'",
    options: [
      { label: "Agree; FIFO is industry standard", score: -2,
        why: "Common myth. The conventional principle in Malaysia is LIFO (Last In, First Out) within similar roles, unless documented business reasons justify otherwise. FIFO without justification invites unjust-dismissal claims." },
      { label: "Apply LIFO within affected roles, document the business case, give statutory notice and benefits", score: 10,
        why: "Solid. LIFO is the default; deviations must be documented and defensible. Notice and termination benefits per the Employment (Termination and Lay-Off Benefits) Regulations 1980 are required for eligible employees." },
      { label: "Offer voluntary separation packages first, then LIFO if shortfall remains", score: 8,
        why: "Pragmatic and defensible. VSS reduces involuntary retrenchments and minimises claims, then LIFO for any remaining gap." },
      { label: "Pay one month's salary in lieu and skip notice for everyone", score: -4,
        why: "Notice rules are statutory floors, and termination benefits depend on length of service and salary band. Skipping process invites Industrial Court action." }
    ] },

  // ---- Boss battle (hardest) ----
  { id: "b1", type: "mcq", law: "EA1955", topic: "termination", diff: 5,
    text: "An employee earning RM6,500 is dismissed for misconduct without a domestic inquiry. Which statement most accurately reflects current law?",
    options: ["EA 1955 doesn't apply at this salary; he has no recourse", "EA 1955 applies (post-2023 extension), but the IRA 1967 Section 20 unjust-dismissal route is the primary remedy regardless of salary", "He must sue under contract law only", "He may file in the Sessions Court but not the Industrial Court"], answer: 1,
    why: "EA 1955 was extended to all employees in 2023 (with some carve-outs for certain entitlements above RM4,000). The IRA 1967 unjust-dismissal route under Section 20 is available to virtually all employees, regardless of salary band." },
  { id: "b2", type: "mcq", law: "EA1955", topic: "wages", diff: 5,
    text: "A salesperson is paid commission only. The employer argues wage protection rules don't apply. Best analysis:",
    options: ["Correct — commission isn't 'wages'", "Wrong — 'wages' under Section 2 includes any payment due in respect of work done, including commission, with limited carve-outs", "Only true if the contract says so", "Only correct if the employee earns above RM4,000"], answer: 1,
    why: "Section 2 defines 'wages' broadly. Commissions earned for work performed generally fall within wages, attracting protections like timely payment and lawful deductions only." },
  { id: "b3", type: "scenario", law: "Sabah", topic: "termination", diff: 5,
    who: "Group HR — Sabah branch",
    setup: "A Kota Kinabalu employee with 7 years' service is dismissed for 'redundancy' but is replaced two weeks later. He files a representation.",
    text: "Most likely outcome at the Industrial Court:",
    options: ["Dismissal upheld — 'redundancy' is a valid ground", "Dismissal set aside — replacement undermines the redundancy ground; back-wages and possibly reinstatement", "Dismissed automatically because Sabah Labour Ordinance, not IRA, applies", "No remedy because the company is in Sabah"], answer: 1,
    why: "IRA 1967 applies in Sabah. Replacing a 'redundant' employee shortly after dismissal typically defeats the redundancy defence. The Court frequently orders back-wages (capped) and may order reinstatement or compensation in lieu." },

  // ============================================================
  // EXPANDED BANK — Wages
  // ============================================================
  { id: "w5", type: "mcq", law: "EA1955", topic: "wages", diff: 2,
    text: "An employer can lawfully deduct from wages WITHOUT the employee's written consent for:",
    options: ["A gym membership the boss thinks is a good idea", "Employees Provident Fund (EPF) contributions", "Cost of unsold inventory", "A 'lateness fine' of RM50"], answer: 1,
    why: "Section 24 only allows specific deductions without consent — overpaid wages, statutory deductions like EPF/SOCSO, court-ordered amounts, etc. Discretionary fines and personal-benefit charges are not on that list." },
  { id: "w6", type: "mcq", law: "EA1955", topic: "wages", diff: 3,
    text: "Excluding statutory contributions and overpayments, the maximum total deduction from wages in any one wage period is:",
    options: ["25%", "50%", "75%", "100%"], answer: 1,
    why: "Section 24(8): total deductions in any one wage period cannot exceed 50% of wages earned in that period (excluding overpayments, statutory deductions, court orders, and similar carve-outs)." },
  { id: "w7", type: "tf", law: "EA1955", topic: "wages", diff: 2,
    text: "Failure to pay wages within 7 days after the end of the wage period is an offence under EA 1955.",
    options: ["True", "False"], answer: 0,
    why: "Section 19 read with Section 99A — late payment of wages beyond the 7-day window is an offence carrying penalties for the employer." },
  { id: "w8", type: "mcq", law: "EA1955", topic: "wages", diff: 3,
    text: "Salary RM2,000 + fixed monthly allowances of RM500 (housing) and RM300 (transport). For overtime calculation, the 'ordinary rate of pay' should generally be based on:",
    options: ["Basic salary only (RM2,000)", "Basic + housing only (RM2,500)", "Basic + all fixed monthly allowances (RM2,800)", "Whatever the contract says"], answer: 2,
    why: "Section 60I — 'ordinary rate of pay' generally includes fixed monthly allowances. Variable items (commission, bonuses, OT itself) are excluded, but fixed allowances form part of the base for OT calculation." },
  { id: "w9", type: "mcq", law: "EA1955", topic: "wages", diff: 2,
    text: "Wages must be paid in:",
    options: ["Goods or vouchers if cheaper", "Legal tender (cash, cheque, or bank transfer subject to conditions)", "Cryptocurrency if both parties agree", "Any form the employer chooses"], answer: 1,
    why: "Section 25/25A — wages must be paid in legal tender. Cheque or direct bank credit are permitted subject to conditions. The 'truck system' (paying in goods) is generally prohibited." },
  { id: "w10", type: "mcq", law: "EA1955", topic: "wages", diff: 2,
    text: "An employee resigns mid-month. When must the final wages be paid?",
    options: ["On the next regular pay day", "On the day the termination takes effect (general rule under Section 20)", "Within 30 days", "Whenever convenient"], answer: 1,
    why: "Section 20: where the contract is terminated by either party, all wages earned and not yet paid must be paid on the day the termination takes effect (with limited exceptions for short-notice terminations)." },
  { id: "w11", type: "tf", law: "EA1955", topic: "wages", diff: 1,
    text: "Wages may be paid by direct credit into the employee's bank account.",
    options: ["True", "False"], answer: 0,
    why: "Section 25A permits payment by bank transfer with the employee's authorisation. Direct deposit is now the predominant method in Malaysian workplaces." },
  { id: "w12", type: "mcq", law: "EA1955", topic: "wages", diff: 2,
    text: "The Minimum Wages Order 2022 (RM1,500) applies:",
    options: ["Only in Peninsular Malaysia", "Only to companies with 5 or more employees, permanently", "Nationally, with phased application initially based on employer size", "Only to Malaysian citizens"], answer: 2,
    why: "The 2022 Order set RM1,500 as the national minimum wage. Smaller employers (≤5 employees) initially had a delayed effective date that has since lapsed." },

  // ============================================================
  // EXPANDED BANK — Hours
  // ============================================================
  { id: "h4", type: "mcq", law: "EA1955", topic: "hours", diff: 1,
    text: "The maximum number of consecutive hours an employee can be required to work without a rest period is:",
    options: ["4 hours", "5 hours", "6 hours", "8 hours"], answer: 1,
    why: "Section 60A(1)(b): no employee shall work more than five consecutive hours without a period of leisure of not less than thirty minutes." },
  { id: "h5", type: "tf", law: "EA1955", topic: "hours", diff: 2,
    text: "Shift workers may, under Section 60C, lawfully work more than 8 hours on a particular day provided the average over a defined cycle stays within statutory limits.",
    options: ["True", "False"], answer: 0,
    why: "Section 60C provides a shift-work framework where daily hours can exceed 8 (within bounds), as long as the averaged hours over a defined period remain within the statutory limits." },
  { id: "h6", type: "tf", law: "EA1955", topic: "hours", diff: 1,
    text: "Working overtime is always voluntary — an employer can never require an employee to work overtime.",
    options: ["True", "False"], answer: 1,
    why: "EA 1955 permits employers to require overtime within statutory limits (max 12 hours per day total work, max 104 hours OT per month) and at the prescribed rates. Refusal rights apply only in narrow circumstances." },
  { id: "h7", type: "mcq", law: "EA1955", topic: "hours", diff: 1,
    text: "The minimum number of paid public holidays an employee is entitled to per year is:",
    options: ["8", "10", "11", "14"], answer: 2,
    why: "Section 60D: at least 11 gazetted paid public holidays per year — 5 mandatory and the remaining selected by the employer or as gazetted in the relevant state." },
  { id: "h8", type: "mcq", law: "EA1955", topic: "hours", diff: 3,
    text: "A monthly-rated employee whose normal day is 8 hours works 6 hours on her rest day. For that work (before any overtime), she is entitled to:",
    options: ["Half day's wages", "One day's wages", "Two days' wages", "One and a half day's wages"], answer: 1,
    why: "Section 60(3): for monthly-rated employees, work on a rest day exceeding half but not exceeding the normal hours = one day's wages at the ordinary rate. Hours beyond the normal day attract OT at the rest-day rate." },
  { id: "h9", type: "mcq", law: "EA1955", topic: "hours", diff: 2,
    text: "An employee who is required to be at the workplace and at the employer's disposal but performs no actual tasks during that time:",
    options: ["Is not entitled to wages for that time", "Is generally treated as working time and entitled to wages", "Is paid at half rate", "Depends entirely on the contract"], answer: 1,
    why: "Time during which the employee is at the employer's disposal at the workplace is generally working time, regardless of whether tasks are actively assigned in that interval." },
  { id: "h10", type: "mcq", law: "EA1955", topic: "hours", diff: 2,
    text: "For overtime worked on a normal weekday, OT pay is 1.5×. For overtime worked on a rest day (beyond normal hours), the rate jumps to:",
    options: ["1.5× hourly rate", "2× hourly rate", "2.5× hourly rate", "3× hourly rate"], answer: 1,
    why: "Section 60(3): for hours worked on a rest day in excess of the normal hours of work, OT is at not less than 2× the hourly rate of pay. (Public-holiday OT goes up to 3×.)" },

  // ============================================================
  // EXPANDED BANK — Leave & Benefits
  // ============================================================
  { id: "l6", type: "mcq", law: "EA1955", topic: "leave", diff: 2,
    text: "An employee with 5 years and 1 month of service has minimum annual leave entitlement of:",
    options: ["8 days", "12 days", "16 days", "20 days"], answer: 2,
    why: "Section 60E: 5+ years of service = 16 days minimum annual leave." },
  { id: "l7", type: "mcq", law: "EA1955", topic: "leave", diff: 2,
    text: "An employee with 7 years of service has paid sick leave entitlement of:",
    options: ["14 days/year", "18 days/year", "22 days/year", "30 days/year"], answer: 2,
    why: "Section 60F: 5+ years of service = 22 days of paid sick leave per year (where no hospitalisation is needed). Aggregate cap with hospitalisation is 60 days/year." },
  { id: "l8", type: "tf", law: "EA1955", topic: "leave", diff: 2,
    text: "Paid sick leave can be claimed without a medical certificate from a registered medical practitioner.",
    options: ["True", "False"], answer: 1,
    why: "Section 60F requires a medical certificate from a registered medical/dental practitioner (or government-approved practitioner). Without a valid MC, paid sick leave entitlement does not generally apply." },
  { id: "l9", type: "mcq", law: "EA1955", topic: "leave", diff: 2,
    text: "Maternity allowance eligibility under EA 1955 requires the employee to have been employed:",
    options: ["At least 90 days during the 9 months before confinement, AND at any time during the 4 months before", "At least 6 months continuously", "At least 1 year continuously", "At any time during the 12 months before"], answer: 0,
    why: "Section 37 — eligibility requires (a) employment at any time in the 4 months immediately before confinement, AND (b) at least 90 days of employment during the 9 months immediately before confinement." },
  { id: "l10", type: "mcq", law: "EA1955", topic: "leave", diff: 2,
    text: "Paternity leave under EA 1955 (Section 60FA) requires the male employee to be:",
    options: ["Married, employed at least 12 months by the same employer, with notice of pregnancy at least 30 days before expected confinement", "Single or married, with at least 6 months service", "Married only, no service requirement", "Married, employed at least 3 months, no notice required"], answer: 0,
    why: "Section 60FA: married, at least 12 months' continuous service with the same employer immediately before commencement of leave, and notification of the employer of the spouse's pregnancy at least 30 days before the expected confinement (or as early as possible)." },
  { id: "l11", type: "tf", law: "EA1955", topic: "leave", diff: 2,
    text: "Annual leave that is not used in the year of entitlement is automatically carried forward without limit.",
    options: ["True", "False"], answer: 1,
    why: "EA 1955 sets the floor entitlement, not a perpetual carry-forward right. Carry-forward is determined by the employment contract or employer policy." },
  { id: "l12", type: "mcq", law: "EA1955", topic: "leave", diff: 2,
    text: "Hospitalisation leave under EA 1955 is capped at:",
    options: ["30 days/year", "45 days/year", "60 days/year (aggregate with sick leave)", "Unlimited"], answer: 2,
    why: "Section 60F: up to 60 days of hospitalisation leave per year, with the aggregate of paid sick leave (including hospitalisation) capped at 60 days per year." },
  { id: "l13", type: "mcq", law: "EA1955", topic: "leave", diff: 3,
    text: "EA 1955 currently provides statutory adoption leave of:",
    options: ["60 consecutive days, mirroring maternity leave", "30 days", "7 days", "None — adoption leave is contractual / employer policy only"], answer: 3,
    why: "EA 1955 does not provide a statutory adoption-leave entitlement. Where granted, adoption leave is a contractual benefit." },
  { id: "l14", type: "tf", law: "EA1955", topic: "leave", diff: 2,
    text: "Annual leave can be encashed (paid out instead of taken) only by mutual agreement, and is not an automatic right.",
    options: ["True", "False"], answer: 0,
    why: "Annual leave is intended for rest. Encashment is permitted on termination of employment for accrued unused leave, but during employment is generally subject to mutual agreement and the contract." },
  { id: "l15", type: "mcq", law: "EA1955", topic: "leave", diff: 3,
    text: "A 4-month-pregnant employee is dismissed for 'performance issues' shortly after disclosing her pregnancy. Most accurate position:",
    options: ["Lawful — performance is a valid ground", "Possibly unlawful — Section 41A shifts the burden to the employer to prove the dismissal is on grounds entirely unrelated to pregnancy", "Lawful only if 30 days' notice given", "Lawful only if she earns above RM4,000"], answer: 1,
    why: "Section 41A protects pregnant employees during the maternity protection period. If dismissed, the employer bears the burden of proving the dismissal was on grounds entirely unrelated to pregnancy." },

  // ============================================================
  // EXPANDED BANK — Termination & Dismissal
  // ============================================================
  { id: "t5", type: "mcq", law: "EA1955", topic: "termination", diff: 3,
    text: "Under the Employment (Termination & Lay-Off Benefits) Regulations 1980, an employee with 3 years of service receives termination benefits at:",
    options: ["10 days' wages per year", "15 days' wages per year", "20 days' wages per year", "30 days' wages per year"], answer: 1,
    why: "Reg 6: <2 years → 10 days/yr; 2 to <5 years → 15 days/yr; 5+ years → 20 days/yr. Pro-rated for incomplete years." },
  { id: "t6", type: "tf", law: "EA1955", topic: "termination", diff: 2,
    text: "Since the 2022 amendments, EA 1955 applies only to employees earning RM4,000 and below.",
    options: ["True", "False"], answer: 1,
    why: "From 1 January 2023, EA 1955 applies to all employees regardless of salary. The RM4,000 threshold remains relevant for certain specific entitlements." },
  { id: "t7", type: "mcq", law: "EA1955", topic: "termination", diff: 4,
    text: "'Constructive dismissal' arises when:",
    options: ["An employee resigns voluntarily for personal reasons", "The employer's fundamental breach of contract effectively forces the employee to resign", "The employee is rude", "Probation is extended"], answer: 1,
    why: "Constructive dismissal is treated as dismissal at the employer's instance — the employee resigns due to a repudiatory breach by the employer. The employee can claim under IRA 1967 Section 20." },
  { id: "t8", type: "mcq", law: "EA1955", topic: "termination", diff: 4,
    text: "The Industrial Court typically caps back-wages for unjust dismissal of a confirmed employee at:",
    options: ["6 months", "12 months", "24 months", "Unlimited"], answer: 2,
    why: "Industrial Court Practice Note 1 of 1987 (and successive guidance) generally caps back-wages at 24 months for confirmed employees and 12 months for probationers, subject to the Court's discretion." },
  { id: "t9", type: "mcq", law: "EA1955", topic: "termination", diff: 3,
    text: "Summary dismissal for misconduct under Section 13(2) requires:",
    options: ["No process — misconduct speaks for itself", "A written warning only", "A domestic inquiry; misconduct must be proven on the balance of probabilities", "The employee's consent"], answer: 2,
    why: "Section 14 — even for summary dismissal for misconduct, due inquiry must be held. The misconduct must be established on the balance of probabilities at the inquiry." },
  { id: "t10", type: "mcq", law: "EA1955", topic: "termination", diff: 3,
    text: "A probationer dismissed without due inquiry:",
    options: ["Has no recourse", "May still file an unjust-dismissal claim under IRA 1967 Section 20", "Can only seek contractual damages", "Can only complain to EPF"], answer: 1,
    why: "Probationers enjoy substantially the same protection against unjust dismissal as confirmed employees and may file under IRA 1967 Section 20 within 60 days." },
  { id: "t11", type: "tf", law: "EA1955", topic: "termination", diff: 3,
    text: "A properly executed Voluntary Separation Scheme (VSS) with a full-and-final-settlement release generally bars later unjust-dismissal claims.",
    options: ["True", "False"], answer: 0,
    why: "Where the VSS is genuinely voluntary, with full disclosure, and signed with understanding, the release typically bars subsequent Section 20 claims." },
  { id: "t12", type: "mcq", law: "EA1955", topic: "termination", diff: 3,
    text: "When retrenchment is genuinely necessary, the conventional Malaysian principle for selecting employees within the same role is:",
    options: ["First-In-First-Out (FIFO)", "Last-In-First-Out (LIFO)", "Random", "By age"], answer: 1,
    why: "LIFO is the conventional default. Departures from LIFO must be supported by clear, defensible business reasons or risk an unjust-dismissal finding." },
  { id: "t13", type: "mcq", law: "EA1955", topic: "termination", diff: 4,
    text: "The most defensible process for dismissing an employee for poor performance is:",
    options: ["Single written warning then termination", "A documented Performance Improvement Plan (PIP) with measurable targets and review milestones, then due inquiry if no improvement", "Termination with severance only", "Quiet sidelining"], answer: 1,
    why: "A documented PIP with measurable targets, support, and review milestones — combined with due inquiry where dismissal is contemplated — is the gold standard for performance-based dismissals to withstand Industrial Court scrutiny." },
  { id: "t14", type: "tf", law: "EA1955", topic: "termination", diff: 2,
    text: "On termination, an employee is entitled to a Certificate of Service from the employer (on request) stating dates of employment and type of work.",
    options: ["True", "False"], answer: 0,
    why: "Section 90 — an employer must, on request, give a written certificate stating the dates of employment and the kind of work performed." },
  { id: "t15", type: "mcq", law: "EA1955", topic: "termination", diff: 3,
    text: "'Garden leave' — paying an employee on notice while requiring them not to attend work — is enforceable in Malaysia:",
    options: ["Always", "Only if expressly contracted for or with employee's consent", "Never", "Only for senior management"], answer: 1,
    why: "Garden leave is generally enforceable only when expressly provided in the contract or consented to. Courts balance the employer's legitimate interests against the employee's right to work." },
  { id: "t16", type: "mcq", law: "EA1955", topic: "termination", diff: 5,
    text: "An employee files an IRA 1967 Section 20 representation on day 65 after dismissal. Most likely outcome:",
    options: ["Accepted with leave", "Out of time and rejected", "Referred to civil court", "Mediated automatically"], answer: 1,
    why: "Section 20 imposes a strict 60-day limitation. Late filings are typically rejected; extensions are rare and require exceptional circumstances." },

  // ============================================================
  // EXPANDED BANK — Recruitment, Compliance, Statutory Schemes
  // ============================================================
  { id: "r4", type: "mcq", law: "EA1955", topic: "compliance", diff: 1,
    text: "The standard employer EPF contribution rate for an employee earning RM4,000/month is:",
    options: ["7%", "11%", "12%", "13%"], answer: 3,
    why: "EPF Act 1991 — employer contribution is 13% for monthly wages of RM5,000 and below; 12% for wages above RM5,000." },
  { id: "r5", type: "mcq", law: "EA1955", topic: "compliance", diff: 1,
    text: "SOCSO (PERKESO) coverage in Malaysia:",
    options: ["Covers Malaysian citizens only", "Covers only employees earning below RM4,000", "Covers all employees including foreign workers (Employment Injury Scheme since 2019)", "Covers only manual workers"], answer: 2,
    why: "Since 2019, SOCSO's Employment Injury Scheme was extended to cover foreign workers. Coverage is mandatory for virtually all employees." },
  { id: "r6", type: "mcq", law: "EA1955", topic: "compliance", diff: 1,
    text: "The Employment Insurance System (EIS) is administered by:",
    options: ["EPF", "SOCSO (PERKESO)", "Inland Revenue Board", "HRD Corp"], answer: 1,
    why: "EIS — established under the Employment Insurance System Act 2017 — is administered by SOCSO. Provides job-search allowance and reskilling support." },
  { id: "r7", type: "mcq", law: "EA1955", topic: "compliance", diff: 2,
    text: "The HRD Corp levy paid by registered employers is generally:",
    options: ["0.5% of monthly wages", "1% of monthly wages", "Equal employer/employee split", "Only paid by manufacturers"], answer: 1,
    why: "Pembangunan Sumber Manusia Berhad Act 2001 — registered employers pay 1% of each employee's monthly wages (0.5% for some categories). Coverage was significantly expanded in 2021." },
  { id: "r8", type: "mcq", law: "EA1955", topic: "compliance", diff: 2,
    text: "Under the Occupational Safety and Health Act 1994, an employer with 40 or more employees must:",
    options: ["Provide safety bonuses", "Establish a Safety and Health Committee", "Issue safety helmets only", "Buy insurance only"], answer: 1,
    why: "Section 30 OSHA 1994 requires employers with 40+ employees to establish a Safety and Health Committee with both management and employee representation." },
  { id: "r9", type: "mcq", law: "EA1955", topic: "compliance", diff: 2,
    text: "Employing a foreign worker without a valid work pass primarily breaches:",
    options: ["The Immigration Act 1959/63 (and may engage anti-trafficking / forced labour provisions)", "Penal Code only", "Companies Act 2016", "Income Tax Act"], answer: 0,
    why: "Hiring without a valid pass primarily breaches the Immigration Act 1959/63 (employer offence). EA 1955 anti-discrimination and Section 90B forced-labour provisions can also apply." },
  { id: "r10", type: "tf", law: "EA1955", topic: "compliance", diff: 2,
    text: "Probationers do not enjoy the protections of EA 1955.",
    options: ["True", "False"], answer: 1,
    why: "Probationers are 'employees' under EA 1955 from day one and enjoy nearly all protections, including the ability to file unjust-dismissal claims under IRA 1967 Section 20." },
  { id: "r11", type: "mcq", law: "EA1955", topic: "recruitment", diff: 2,
    text: "A fixed-term contract repeatedly renewed without genuine business justification may be reclassified by the Industrial Court as:",
    options: ["Null", "A permanent contract", "A casual contract", "Volunteer work"], answer: 1,
    why: "Sham fixed-term contracts (used to deny benefits) are routinely reclassified as permanent. The 'genuine business reason' test applies to determine if the fixed term is bona fide." },
  { id: "r12", type: "mcq", law: "EA1955", topic: "recruitment", diff: 3,
    text: "A hiring manager asks a female applicant her marital status and intentions about children. Most accurate analysis under Section 60M:",
    options: ["Permitted — just casual conversation", "Strong indication of unlawful discrimination if used in selection", "Permitted if she answers voluntarily", "Allowed in interviews but not on application forms"], answer: 1,
    why: "Section 60M empowers the DG to inquire into discrimination disputes. Asking and using marital/parenthood status in selection is a strong indicator of unlawful gender/marital-status discrimination." },
  { id: "r13", type: "tf", law: "EA1955", topic: "compliance", diff: 2,
    text: "Background checks on a job applicant can be lawfully carried out without informing the applicant.",
    options: ["True", "False"], answer: 1,
    why: "Personal Data Protection Act 2010 generally requires notice and a lawful basis (often consent) for processing personal data." },

  // ============================================================
  // EXPANDED BANK — Sabah Labour Ordinance
  // ============================================================
  { id: "sb4", type: "mcq", law: "Sabah", topic: "compliance", diff: 2,
    text: "The primary regulator for labour matters in Sabah is:",
    options: ["Jabatan Tenaga Kerja Sabah (Labour Department Sabah)", "LHDN Sabah", "Companies Commission of Malaysia", "EPF Sabah"], answer: 0,
    why: "Jabatan Tenaga Kerja Sabah administers the Sabah Labour Ordinance and is the primary point of contact for inspections, complaints, and dispute resolution." },
  { id: "sb5", type: "mcq", law: "Sabah", topic: "termination", diff: 3,
    text: "A Sabah employee dismissed without just cause wishes to challenge the dismissal. The applicable industrial-relations machinery is:",
    options: ["A separate Sabah Industrial Relations Ordinance", "The federal Industrial Relations Act 1967 — Section 20 representation", "Customary law", "Sabah Civil High Court only"], answer: 1,
    why: "IRA 1967 is federal legislation that applies in Sabah. Unjust-dismissal claims are filed under Section 20 with the Director General of Industrial Relations within 60 days." },
  { id: "sb6", type: "tf", law: "Sabah", topic: "wages", diff: 1,
    text: "The national Minimum Wages Order applies in Sabah.",
    options: ["True", "False"], answer: 0,
    why: "Minimum Wages Orders are made under the National Wages Consultative Council Act 2011 — a federal statute applicable throughout Malaysia, including Sabah and Sarawak." },
  { id: "sb7", type: "mcq", law: "Sabah", topic: "hours", diff: 2,
    text: "A worker in Lahad Datu, Sabah, is denied a weekly rest day. The relevant statutory floor is:",
    options: ["No rest day required in Sabah", "At least one rest day per week under the Sabah Labour Ordinance", "Two rest days per fortnight only", "Sundays only"], answer: 1,
    why: "The Sabah Labour Ordinance requires at least one rest day per week, mirroring the EA 1955 standard." },

  // ============================================================
  // EXPANDED BANK — Sarawak Labour Ordinance
  // ============================================================
  { id: "sk4", type: "mcq", law: "Sarawak", topic: "compliance", diff: 2,
    text: "Industrial relations and trade union matters in Sarawak are governed by:",
    options: ["A separate Sarawak Industrial Relations Ordinance", "The federal Industrial Relations Act 1967", "Customary adat", "Sabah Labour Ordinance"], answer: 1,
    why: "IRA 1967 is federal legislation applying in Sarawak. The Sarawak Labour Ordinance (Cap. 76) governs day-to-day employment terms; industrial-relations machinery is federal." },
  { id: "sk5", type: "mcq", law: "Sarawak", topic: "termination", diff: 3,
    text: "Termination and lay-off benefits for eligible Sarawak employees are governed by:",
    options: ["The Sarawak Labour Ordinance and its subsidiary legislation", "The federal Employment (Termination & Lay-Off Benefits) Regulations 1980 directly", "Common law only", "A collective bargaining agreement only"], answer: 0,
    why: "The Sarawak Labour Ordinance (Cap. 76) and its subsidiary legislation contain Sarawak-specific termination/lay-off benefit rules." },
  { id: "sk6", type: "tf", law: "Sarawak", topic: "hours", diff: 2,
    text: "Recent amendments to the Sarawak Labour Ordinance have aligned the maximum normal weekly working hours with the EA 1955 reduction to 45 hours.",
    options: ["True", "False"], answer: 0,
    why: "Sarawak's Labour Ordinance has been amended to broadly harmonise key working-hour limits with the EA 1955 reforms — including the 45-hour weekly cap." },
  { id: "sk7", type: "mcq", law: "Sarawak", topic: "termination", diff: 3,
    text: "An IT engineer in Kuching is dismissed without inquiry for 'loss of confidence.' Correct forum:",
    options: ["Sarawak State Court only", "Federal Industrial Court via IRA 1967 Section 20 representation", "Civil High Court only", "Sarawak Labour Officer only"], answer: 1,
    why: "Unjust-dismissal claims are filed under IRA 1967 Section 20 (federal) with the Director General of Industrial Relations and may be referred to the Industrial Court — applicable in Sarawak." },

  // ============================================================
  // EXPANDED BANK — Scenarios
  // ============================================================
  { id: "sc4", type: "scenario", law: "EA1955", topic: "leave", diff: 3,
    who: "HR Lead, mid-size manufacturing",
    setup: "Faridah, 5 months pregnant, applies in writing to work from home 3 days a week for the rest of her pregnancy. Your COO says: 'We don't do remote work — say no, no need to write back.'",
    text: "Most defensible course under EA 1955?",
    options: ["Refuse verbally — operational reasons", "Ignore the request", "Assess whether the role permits flexible work; respond in writing within 60 days; if refusing, give written reasons (Sections 60P–60Q)", "Approve everything to avoid disputes"], answer: 2,
    why: "Sections 60P–60Q (added 2022) — an employee may apply in writing for a flexible working arrangement. The employer must respond in writing within 60 days; if refusing, written reasons must be given." },
  { id: "sc5", type: "scenario", law: "EA1955", topic: "termination", diff: 4,
    who: "Ops Manager, F&B chain",
    setup: "A supervisor reports that an employee, Daud, was caught on CCTV pocketing RM50 from the till. Your impulse is to terminate him on the spot.",
    text: "Best practice next step?",
    options: ["Terminate immediately — theft is serious misconduct", "Suspend on not less than half pay pending domestic inquiry; issue written charges; let Daud be heard before deciding", "Issue a verbal warning", "Forward to police only and wait"], answer: 1,
    why: "Section 14(2) permits suspension on not less than half pay during the inquiry. Even with CCTV, skipping due inquiry risks the dismissal being set aside as without just cause and excuse." },
  { id: "sc6", type: "scenario", law: "EA1955", topic: "wages", diff: 2,
    who: "Founder, 8-person agency",
    setup: "Your contract designer earns RM3,500 monthly plus a fixed RM500 transport allowance. He worked 10 hours OT last month. You calculated OT on RM3,500.",
    text: "What's the issue?",
    options: ["Nothing — base salary is correct", "You should include the fixed RM500 allowance; ordinary rate of pay typically includes fixed monthly allowances", "OT should be on basic minus allowances", "Designers are exempt from OT"], answer: 1,
    why: "Section 60I — fixed monthly allowances generally form part of 'ordinary rate of pay' for OT calculation. Excluding the RM500 transport allowance underpays the employee." },
  { id: "sc7", type: "scenario", law: "EA1955", topic: "recruitment", diff: 3,
    who: "Hiring Manager",
    setup: "You're hiring for a customer-service role. A strong candidate discloses a hearing impairment correctable with assistive tech that costs about RM800.",
    text: "Most aligned course of action?",
    options: ["Reject — lower-cost candidates available", "Hire if she's the best candidate; provide reasonable accommodation; document the assessment", "Hire only if she pays for the assistive tech", "Hire on a lower wage to offset the cost"], answer: 1,
    why: "Section 60M's anti-discrimination scope includes disability. Reasonable accommodation aligned with the role is standard practice; refusing solely on accommodation cost invites discrimination findings." },

  // ============================================================
  // EXPANDED BANK — Spot the Violation
  // ============================================================
  { id: "sv3", type: "violation", law: "EA1955", topic: "recruitment", diff: 3,
    setup: "A job ad reads: 'Marketing executive needed. Female only, single, age 22–28, must be Chinese-speaking. Salary RM3,000.'",
    text: "Which protected grounds are most likely violated?",
    options: ["Gender, marital status, age, race", "Only race", "Only age", "None — preferences are allowed"], answer: 0,
    why: "Section 60M empowers the DG to inquire into discrimination disputes. The advertisement signals discrimination on multiple protected grounds — gender, marital status, age, and likely race." },
  { id: "sv4", type: "violation", law: "EA1955", topic: "hours", diff: 2,
    setup: "A delivery hub schedules riders for 6 days a week, 9 hours per day, with no rest day. Lunch breaks are 15 minutes.",
    text: "Which violations apply?",
    options: ["No weekly rest day (s.59) and inadequate rest period after 5 consecutive hours (s.60A(1)(b))", "Only the rest day issue", "Only the rest-period issue", "No violation — riders are independent contractors"], answer: 0,
    why: "Sections 59 and 60A(1)(b): one rest day per week minimum, and at least 30 minutes' leisure after 5 consecutive hours of work. Misclassification of riders as contractors is a separate issue assessed on substance, not the label." },

  // ============================================================
  // EXPANDED BANK — Decision Simulator
  // ============================================================
  { id: "ds3", type: "decision", law: "EA1955", topic: "compliance", diff: 4,
    who: "You — Founder/CEO",
    setup: "Your finance lead asks: 'Can we treat the new hires as interns for the first 6 months to avoid EPF and SOCSO contributions?'",
    options: [
      { label: "Yes — call them interns to save cost", score: -8,
        why: "Substance over form. If the role isn't a genuine internship aligned with study, the 'intern' label is a sham. EPF/SOCSO obligations attach by the nature of the working relationship." },
      { label: "No — if the role is a real job, statutory contributions apply regardless of title", score: 10,
        why: "Correct. Misclassification exposes the company to back-contributions, penalties, and possible offence proceedings." },
      { label: "Yes for the first 3 months only", score: -5,
        why: "No statutory grace period exists for sham classification." },
      { label: "Ask them to sign a waiver", score: -6,
        why: "Statutory contributions cannot be waived by the employee — they are mandatory." }
    ] },
  { id: "ds4", type: "decision", law: "EA1955", topic: "compliance", diff: 3,
    who: "You — Head of People",
    setup: "A reference check on an outgoing employee returns: 'Was she a good employee? Did she steal anything? Why did she leave?'",
    options: [
      { label: "Share everything you know to be helpful", score: -4,
        why: "Risky — defamation exposure if statements aren't verifiable, plus PDPA concerns about disclosing personal data without lawful basis." },
      { label: "Confirm dates of employment and role only; flag separately if asked under specific lawful process", score: 9,
        why: "Standard best practice. Limits PDPA and defamation risk while remaining truthful." },
      { label: "Refuse to answer at all", score: 5,
        why: "Defensible but unhelpful. Factual confirmation of employment dates is generally low-risk." },
      { label: "Make up something neutral to be safe", score: -8,
        why: "Don't fabricate. Even 'neutral' lies create exposure for the employer." }
    ] },

  // ============================================================
  // EXPANDED BANK — Boss Battle (hardest)
  // ============================================================
  { id: "b4", type: "mcq", law: "EA1955", topic: "termination", diff: 5,
    text: "A manager sets up a side business that competes with the employer using the employer's contacts. Discovered after termination on unrelated grounds. Best legal route for the employer:",
    options: ["No remedy — he's already terminated", "Civil claim for breach of fiduciary duty / confidentiality / contract (post-employment restraints, where enforceable) and unjust enrichment, plus possible criminal liability for criminal breach of trust", "Industrial Court claim", "Report only to MyEG"], answer: 1,
    why: "Post-termination breaches of fiduciary duty and use of confidential information are pursued in civil courts. CBT under the Penal Code may apply to dishonest misappropriation. Restraint clauses must be reasonable to be enforceable under Section 28 Contracts Act 1950." },
  { id: "b5", type: "mcq", law: "Sabah", topic: "compliance", diff: 5,
    text: "A Sabah-based manufacturer is found running an unregistered worker dormitory. The most directly applicable statute is:",
    options: ["EA 1955 — irrelevant in Sabah", "Workers' Minimum Standards of Housing and Amenities Act 1990 (Act 446), as extended/applied to Sabah", "Companies Act 2016", "Customary land law"], answer: 1,
    why: "Act 446 was extended to Sabah and Sarawak by amendment, requiring accommodation certification, minimum housing standards, and registration. Non-compliance carries fines per worker." }
];
